### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by fulldecent** [daisukeokaoss/DOFlatButton_old#1]
Please add cocoapods and carthage

**Comment by daisukeokaoss** [comment]
thank you for notify me!! I will add cocoapod soon!!

**Comment by daisukeokaoss** [comment]
I pushed CocoaPods but not carthage please wait

**Comment by fulldecent** [comment]
Looks great, thank you!

**Comment by fulldecent** [comment]
Thanks for your help. Closing.
